### PR TITLE
Master wip

### PR DESCRIPTION
**Pull request by Daikael**
:thonk:

### CODE REVIEW

**Comment by Ormael7** [comment]
I fixed this part and disabled herm worship so no need for this PR unless you make some diff changes in it

**Comment by Svalkash** [comment]
bruh

**Comment by Jtecx** [comment]
hurray it's no longer conflictingggggg

**Comment by Ormael7** [comment]
Ummmm. Over 2 weeks and you not fixed the code. Conflict not exist but there is still code that will cause potential errors.

**Pull request closed without merging**
